name: Deploy Website

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: production-deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload website via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftp.mtelektrik.id
          username: gh_mte@mtelektrik.id
          password: 3rW[rfZe3b,ifvmq
          port: 21
          protocol: ftps

          local-dir: ./
          server-dir: /

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/.env
            **/.env.*
            package.json
            package-lock.json
            yarn.lock
            pnpm-lock.yaml
            README.md
